
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import ConditionalNavbar from './components/Navbar/ConditionalNavbar';
import { UserProvider } from "./context/user";
import UserWrapper from './components/Wrapper/wrapper';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <UserWrapper>
          {children}
        </UserWrapper>
      </body>
    </html>
  );
}